# Generated by Django 4.2.5 on 2023-09-29 13:54

import avitoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avitoapp', '0002_ad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='preview',
            field=models.ImageField(null=True, blank=True, upload_to=avitoapp.models.ad_preview_directory_path),
        ),
    ]
