# Generated by Django 4.2.5 on 2023-09-29 14:54

import avitoapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avitoapp', '0003_ad_preview_alter_ad_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=avitoapp.models.ad_images_directory_path)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='avitoapp.ad')),
            ],
        ),
    ]
