# Generated by Django 4.2.6 on 2023-10-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avitoapp', '0004_alter_ad_address_adimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='phone',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
